var rows = [
    {
        "id": 0,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Catalogue of Life",
        "dataset_short_name": "COL",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "download_dataset",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.catalogueoflife.org/",
        "api_documentation": "(ChecklistBank) https://www.checklistbank.org/about/API",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 1,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Catalogue of Life eXtended Release",
        "dataset_short_name": "COL-XR",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "classification"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "download_dataset",
            "api",
            "local_installation"
        ],
        "homepage": "",
        "api_documentation": "(ChecklistBank) https://www.checklistbank.org/about/API",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 2,
        "service_name": "GBIF Species Matcher",
        "dataset_name": "GBIF Backbone Taxonomy (2023)",
        "dataset_short_name": "GBIF",
        "notes": "Will probably be replaced by GBIF/COL ChecklistBank name matching",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "file_matching_interface",
            "download_full_from_website",
            "api"
        ],
        "homepage": "https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
        "api_documentation": "https://techdocs.gbif.org/en/openapi/v1/species",
        "direct_matching_restriction": 0,
        "file_matching_restriction": 6000
    },
    {
        "id": 3,
        "service_name": "WFO Plant List",
        "dataset_name": "World Flora Online Plant List",
        "dataset_short_name": "WFO Plant List",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "download_dataset",
            "api",
            "local_installation"
        ],
        "homepage": "https://wfoplantlist.org/",
        "api_documentation": "https://list.worldfloraonline.org/",
        "direct_matching_restriction": 1000000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 4,
        "service_name": "Global Names Verifier",
        "dataset_name": "International Plant Name Index",
        "dataset_short_name": "IPNI",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.ipni.org/",
        "api_documentation": "In preparation according to https://www.ipni.org/about",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 5,
        "service_name": "Kew Names Matching Service",
        "dataset_name": "International Plant Name Index",
        "dataset_short_name": "IPNI",
        "notes": "8 jul 2025: Does work through all records, but matches non",
        "caveats": "Not working",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "open_refine_reconciliation_if"
        ],
        "homepage": "https://www.ipni.org/",
        "api_documentation": "In preparation according to https://www.ipni.org/about",
        "direct_matching_restriction": 1000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 6,
        "service_name": "Kew Names Matching Service",
        "dataset_name": "World Checklist of Vascular Plants",
        "dataset_short_name": "WCVP",
        "notes": "States the PoWo dataset, not WCVP",
        "caveats": "",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website"
        ],
        "homepage": "https://powo.science.kew.org/about-wcvp;",
        "api_documentation": "(rudimentary API) https://barnabywalker.github.io/kewr/reference/download_wcvp.html",
        "direct_matching_restriction": 1000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 7,
        "service_name": "PESI - eu-nomen",
        "dataset_name": "Pan European Species Information Infrastructure  EU - Nomen",
        "dataset_short_name": "PESI",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "algae",
            "animalia",
            "cyanobacteria",
            "fungi",
            "plantae"
        ],
        "geographic_scope": [
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "file_matching_interface"
        ],
        "homepage": "https://www.eu-nomen.eu/portal/",
        "api_documentation": "",
        "direct_matching_restriction": 0,
        "file_matching_restriction": 1000
    },
    {
        "id": 8,
        "service_name": "PESI - eu-nomen",
        "dataset_name": "Euro+Med PlantBase",
        "dataset_short_name": "E+M PlantBase",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "classification"
        ],
        "linkage": [],
        "requirements": [
            "file_matching_interface"
        ],
        "homepage": "https://europlusmed.org/",
        "api_documentation": "",
        "direct_matching_restriction": 0,
        "file_matching_restriction": 1000
    },
    {
        "id": 9,
        "service_name": "rWCVP",
        "dataset_name": "World Checklist of Vascular Plants",
        "dataset_short_name": "WCVP",
        "notes": "",
        "caveats": "",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "download_full_from_website",
            "r_package",
            "local_installation"
        ],
        "homepage": "https://powo.science.kew.org/about-wcvp;",
        "api_documentation": "(rudimentary API) https://barnabywalker.github.io/kewr/reference/download_wcvp.html",
        "direct_matching_restriction": 0,
        "file_matching_restriction": 0
    },
    {
        "id": 10,
        "service_name": "WoRMS Taxon match",
        "dataset_name": "World Register of Marine Species",
        "dataset_short_name": "WoRMS",
        "notes": "",
        "caveats": "Potential erroneous exact matches returned for canonical name only. Erroneous exact match returned for infraspecies when species is found. Erroneous ambiguous match for family when genus is found. Phonetic matching misleading (Lycopodiaceae => Leucopdum)",
        "organism_groups": [
            "marine_only",
            "algae",
            "animalia",
            "cyanobacteria",
            "fungi",
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api"
        ],
        "homepage": "https://www.marinespecies.org",
        "api_documentation": "https://www.marinespecies.org/rest/",
        "direct_matching_restriction": 0,
        "file_matching_restriction": 1500
    },
    {
        "id": 11,
        "service_name": "Taxonomic Name Resolution Service (TNRS)",
        "dataset_name": "World Checklist of Vascular Plants",
        "dataset_short_name": "WCVP",
        "notes": "Very detailed result set with parsed names, author comparison etc. - but upload of local id is not possible. Classification only family.",
        "caveats": "matches infraspecies with species when epithet not found (but unmatched part is mentioned)",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api"
        ],
        "homepage": "https://powo.science.kew.org/about-wcvp;",
        "api_documentation": "(rudimentary API) https://barnabywalker.github.io/kewr/reference/download_wcvp.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 12,
        "service_name": "Taxonomic Name Resolution Service (TNRS)",
        "dataset_name": "World Flora Online Plant List",
        "dataset_short_name": "WFO Plant List",
        "notes": "Very detailed result set with parsed names and separate scoring for name elements - but upload of local id is not possible. Classification: Family column exists, but empty.",
        "caveats": "Old version 2023.06 [8 jul 2025]. Matches infraspecies with species when epithet not found (but unmatched part is mentioned)",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api"
        ],
        "homepage": "https://wfoplantlist.org/",
        "api_documentation": "https://list.worldfloraonline.org/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 13,
        "service_name": "lcvplants",
        "dataset_name": "Leipzig Catalogue of Vascular Plants",
        "dataset_short_name": "LCVP",
        "notes": "An R-Package",
        "caveats": "(not tested)",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "r_package",
            "local_installation"
        ],
        "homepage": "https://github.com/idiv-biodiversity/LCVP",
        "api_documentation": "",
        "direct_matching_restriction": 0,
        "file_matching_restriction": 0
    },
    {
        "id": 14,
        "service_name": "Global Names Verifier",
        "dataset_name": "Algaebase",
        "dataset_short_name": "Algaebase",
        "notes": "Old dataset 2021-10-21 [11 jul 2025]",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "algae",
            "cyanobacteria"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.algaebase.org/",
        "api_documentation": "https://www.algaebase.org/api/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 15,
        "service_name": "Global Names Verifier",
        "dataset_name": "Catalogue of Life",
        "dataset_short_name": "COL",
        "notes": "",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.catalogueoflife.org/",
        "api_documentation": "(ChecklistBank) https://www.checklistbank.org/about/API",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 16,
        "service_name": "Global Names Verifier",
        "dataset_name": "Integrated Taxonomic Information System",
        "dataset_short_name": "I T I S",
        "notes": "Dataset updated 2025-05-23 [11 jul 2025]",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.itis.gov/",
        "api_documentation": "https://www.itis.gov/ws_description.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 17,
        "service_name": "Global Names Verifier",
        "dataset_name": "Paleobiology Database",
        "dataset_short_name": "PaleoBase",
        "notes": "",
        "caveats": "Result does not include orthographic variants present in PaleoBase (\"NoMatch\"). Synonymic names apparently also not included in the dataset. Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "fossil_only",
            "contains_fossils",
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://paleobiodb.org/#/",
        "api_documentation": "https://paleobiodb.org/data1.2/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 18,
        "service_name": "Global Names Verifier",
        "dataset_name": "Tropicos",
        "dataset_short_name": "Tropicos",
        "notes": "Old dataset (last updated 2021-11-12) [12 jul 2025]",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://tropicos.org/home",
        "api_documentation": "http://services.tropicos.org/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 19,
        "service_name": "Global Names Verifier",
        "dataset_name": "World Register of Marine Species",
        "dataset_short_name": "WoRMS",
        "notes": "Dataset updated 2025-05-23 [12 jul 2025]",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "marine_only",
            "algae",
            "animalia",
            "cyanobacteria",
            "fungi",
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.marinespecies.org",
        "api_documentation": "https://www.marinespecies.org/rest/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 20,
        "service_name": "Global Names Verifier",
        "dataset_name": "Encyclopedia of Life",
        "dataset_short_name": "EOL",
        "notes": "Updated 2025-02-04 [12 jul 2025].",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\"). The IDs cited (\"bare-name-#####\") do not resolve to taxon or name page.",
        "organism_groups": [
            "contains_fossils",
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://eol.org/",
        "api_documentation": "https://github.com/EOL/publishing/blob/master/doc/api.md",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 21,
        "service_name": "Global Names Verifier",
        "dataset_name": "iNaturalist Taxonomy",
        "dataset_short_name": "iNaturalist",
        "notes": "Updated 2025-05-1 [12 jul 2025]",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\"). Only accepted names. ID given resolves to taxon page.",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.inaturalist.org/taxa",
        "api_documentation": "https://api.inaturalist.org/v1/docs/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 22,
        "service_name": "Global Names Verifier",
        "dataset_name": "Fungal Names",
        "dataset_short_name": "Fungal Names",
        "notes": "",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "fungi"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://nmdc.cn/fungalnames/",
        "api_documentation": "https://nmdc.cn/fungalnames/towebservice",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 23,
        "service_name": "Global Names Verifier",
        "dataset_name": "Mycobank",
        "dataset_short_name": "Mycobank",
        "notes": "The ID given als \"bare-name-#####\" does not resolve. It not the MycoBank# nor the Index Fungorum ID.",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "fungi"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.mycobank.org/",
        "api_documentation": "On request from Mycobank custodian.",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 24,
        "service_name": "Global Names Verifier",
        "dataset_name": "Index Fungorum",
        "dataset_short_name": "IF",
        "notes": "",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "fungi"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.indexfungorum.org/",
        "api_documentation": "https://www.checklistbank.org/about/API",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 25,
        "service_name": "Global Names Verifier",
        "dataset_name": "GBIF Backbone Taxonomy (2023)",
        "dataset_short_name": "GBIF",
        "notes": "Updated 2024-01-11 [12 jul 2025]",
        "caveats": "Name resolve to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
        "api_documentation": "https://techdocs.gbif.org/en/openapi/v1/species",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 26,
        "service_name": "Global Names Verifier",
        "dataset_name": "NCBI Taxonomy",
        "dataset_short_name": "NCBI",
        "notes": "ID given is the NCBI \"TREE&ID\": https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=#####",
        "caveats": "Name resolved to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.ncbi.nlm.nih.gov/taxonomy",
        "api_documentation": "https://www.ncbi.nlm.nih.gov/home/develop/api/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 27,
        "service_name": "Global Names Verifier",
        "dataset_name": "Le R\u00e9f\u00e9rentiel Taxonomique Taxref",
        "dataset_short_name": "Taxref",
        "notes": "",
        "caveats": "Name resolved to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "fr"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://inpn.mnhn.fr/programme/referentiel-taxonomique-taxref?lg=en",
        "api_documentation": "https://taxref.mnhn.fr/taxref-web/api/doc",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 28,
        "service_name": "Global Names Verifier",
        "dataset_name": "List of Prokaryotic names with Standing in Nomenclature (LPSN)",
        "dataset_short_name": "LPSN",
        "notes": "",
        "caveats": "ID cited does not resolve on website (maybe using API?). A resolvable ID can be formed by replacing spaces in the canonical name with dashes.",
        "organism_groups": [
            "bacteria",
            "cyanobacteria"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "",
        "api_documentation": "https://api.bacdive.dsmz.de/; registration required",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 29,
        "service_name": "Global Names Verifier",
        "dataset_name": "World Checklist of Vascular Plants",
        "dataset_short_name": "WCVP",
        "notes": "An ID is cited but we found no way to resolve it.",
        "caveats": "Name resolved to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://powo.science.kew.org/about-wcvp;",
        "api_documentation": "(rudimentary API) https://barnabywalker.github.io/kewr/reference/download_wcvp.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 30,
        "service_name": "Global Names Verifier",
        "dataset_name": "World Flora Online Plant List",
        "dataset_short_name": "WFO Plant List",
        "notes": "WFO-ID is given in the versioned form (e.g. wfo-0001123862-2024-12) that can be resolved on the WFO Plant List site only. Update on the latest version obviously not automatic (cites Dec 24 [12 jul 2025)",
        "caveats": "Name resolved to other ranks when no exact match is found (\"PartialExact\").",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://wfoplantlist.org/",
        "api_documentation": "https://list.worldfloraonline.org/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 31,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Algaebase",
        "dataset_short_name": "Algaebase",
        "notes": "CLB dataset 304756 (this is the 2021 GNA dataset [12 jul 2025]). Attribute ID (before column \"rank\") resolves at https://www.algaebase.org/search/species/detail/?species_id=##### (for rank species or infraspecies)",
        "caveats": "Dataset not up-to-date [12 jul 2025].",
        "organism_groups": [
            "algae",
            "cyanobacteria"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.algaebase.org/",
        "api_documentation": "https://www.algaebase.org/api/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 32,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Artsdatabanken (Norway) / Nortaxa",
        "dataset_short_name": "Artsdatabanken / Nortaxa",
        "notes": "CLB dataset 2030 [12 jul 2025]",
        "caveats": "",
        "organism_groups": [
            "algae",
            "animalia",
            "cyanobacteria",
            "fungi",
            "plantae"
        ],
        "geographic_scope": [
            "no"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://artsdatabanken.no/",
        "api_documentation": "https://nortaxa.artsdatabanken.no/swagger/index.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 33,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Barcode of Life",
        "dataset_short_name": "BOLD Taxonomy",
        "notes": "CLB dataset 37384 2024-07-19 [12 jul 2025]",
        "caveats": "Dataset not updated?",
        "organism_groups": [
            "algae",
            "animalia",
            "fungi",
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "",
        "api_documentation": "",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 34,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Dyntaxa (Sweden)",
        "dataset_short_name": "Dyntaxa",
        "notes": "CLB dataset 2041 2025-07-08 [12 jul 2025]",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "se"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://biodiversitydata.se/",
        "api_documentation": "https://api.biodiversitydata.se/api.html?urls.primaryName=Species",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 35,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "GBIF Backbone Taxonomy (2023)",
        "dataset_short_name": "GBIF",
        "notes": "CLB dataset 53147 2023-08-28 [12 jul 2025]",
        "caveats": "Dataset will not be updated.",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
        "api_documentation": "https://techdocs.gbif.org/en/openapi/v1/species",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 36,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Integrated Taxonomic Information System",
        "dataset_short_name": "I T I S",
        "notes": "CLB dataset 2144 2025-06-26 [12 jul 2025]",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.itis.gov/",
        "api_documentation": "https://www.itis.gov/ws_description.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 37,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "International Committee on Taxonomy of Viruses (ICTV) Virus Taxonomy: ICTV Master Species List",
        "dataset_short_name": "ICTV",
        "notes": "CLB dataset 1014 2023-06-07 [12 jul 2025]. It is not clear what the alphanumeric attribute \"ID\" refers to.",
        "caveats": "Penultimate release (latest 2024 ratified 2025) [13 jul 2025]",
        "organism_groups": [
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://ictv.global/",
        "api_documentation": "",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 38,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Index Fungorum",
        "dataset_short_name": "IF",
        "notes": "CLB dataset 129659 2024-09-19 [13 jul 2025]",
        "caveats": "CHECK - Name match against this dataset did not yield results (e.g. for name Abrothallus parmotrematis, IF ID 135706",
        "organism_groups": [
            "fungi"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.indexfungorum.org/",
        "api_documentation": "https://www.checklistbank.org/about/API",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 39,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "iNaturalist Taxonomy",
        "dataset_short_name": "iNaturalist",
        "notes": "CLB dataset 139831 2025-07-01 [13 jun 2025]",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "acceptance",
            "classification"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.inaturalist.org/taxa",
        "api_documentation": "https://api.inaturalist.org/v1/docs/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 40,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "International Plant Name Index",
        "dataset_short_name": "IPNI",
        "notes": "CLB dataset 2006 2025-07-06 [13 jun 2025]",
        "caveats": "taxonomic status of all names given as \"provisionally accepted\"",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.ipni.org/",
        "api_documentation": "In preparation according to https://www.ipni.org/about",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 41,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "FinBIF taxon database",
        "dataset_short_name": "Laji.fi",
        "notes": "CLB dataset 290762 2025-06-17 [13 jun 2025]",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "fi"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://info.laji.fi/en/frontpage/mission/",
        "api_documentation": "https://api.laji.fi/explorer/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 42,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Leipzig Catalogue of Vascular Plants",
        "dataset_short_name": "LCVP",
        "notes": "CLB dataset 2262 2022-11-07 [13 jul 2025]",
        "caveats": "Dataset has not been updated for some time.",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://github.com/idiv-biodiversity/LCVP",
        "api_documentation": "",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 43,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Mycobank",
        "dataset_short_name": "Mycobank",
        "notes": "CLB dataset 2002 2025-07-13 [13 jul 2025]",
        "caveats": "",
        "organism_groups": [
            "fungi"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.mycobank.org/",
        "api_documentation": "On request from Mycobank custodian.",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 44,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "NCBI Taxonomy",
        "dataset_short_name": "NCBI",
        "notes": "CLB dataset 2169 2022-03-07 [13 jul 2025]",
        "caveats": "Dataset outdated?",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.ncbi.nlm.nih.gov/taxonomy",
        "api_documentation": "https://www.ncbi.nlm.nih.gov/home/develop/api/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 45,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Paleobiology Database",
        "dataset_short_name": "PaleoBase",
        "notes": "CLB dataset 1174 2025-01-26 [13 jun 2025]",
        "caveats": "ID output with prefix \"txn: \". Result does not include orthographic variants present in PaleoBase (matchType \"none\"). Synonymic names apparently also not included in the dataset.",
        "organism_groups": [
            "fossil_only",
            "contains_fossils",
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://paleobiodb.org/#/",
        "api_documentation": "https://paleobiodb.org/data1.2/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 46,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Species Fungorum [Plus]",
        "dataset_short_name": "Species Fungorum",
        "notes": "CLB dataset 1028 2025-03-31 [13 jun 2025]",
        "caveats": "ID returned is the Index Fungorum Registration Identifier.",
        "organism_groups": [
            "fungi"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.speciesfungorum.org/",
        "api_documentation": "(ChecklistBank) https://www.checklistbank.org/about/API",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 47,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Le R\u00e9f\u00e9rentiel Taxonomique Taxref",
        "dataset_short_name": "Taxref",
        "notes": "CLB dataset 2008 2025-03-10 [13 jul 2025]",
        "caveats": "",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "fr"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://inpn.mnhn.fr/programme/referentiel-taxonomique-taxref?lg=en",
        "api_documentation": "https://taxref.mnhn.fr/taxref-web/api/doc",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 48,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Tropicos",
        "dataset_short_name": "Tropicos",
        "notes": "CLB dataset 310868 2021-11-04 [13 jun 2025]",
        "caveats": "Dataset not updated, source GNI. Tropicos is a nomenclator and provides a taxonomic status only in the context of a bibliographic reference or a project. The status is here erroneously set to \"accepted\" for all matched names.",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://tropicos.org/home",
        "api_documentation": "http://services.tropicos.org/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 49,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "UK Species Inventory / Species Dictionary",
        "dataset_short_name": "UK Species Dictionary",
        "notes": "CLB dataset 7888 2023-02-16 [13 jul 2025]",
        "caveats": "The ID given is the \"Taxon Version Key\". Because it is unique and retained for the historical record, it can serve as a name id (but a name may have several taxon version keys).",
        "organism_groups": [
            "multiple",
            "algae",
            "animalia",
            "bacteria",
            "cyanobacteria",
            "fungi",
            "plantae",
            "virus"
        ],
        "geographic_scope": [
            "it",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.nhm.ac.uk/our-science/data/uk-species.html",
        "api_documentation": "https://docs.ckan.org/en/latest/api/index.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 50,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "World Checklist of Vascular Plants",
        "dataset_short_name": "WCVP",
        "notes": "CLB dataset 2232 2025-05-28 [13 jul 2025]",
        "caveats": "Classification restricted to Family. ID assumed to be persistent.",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://powo.science.kew.org/about-wcvp;",
        "api_documentation": "(rudimentary API) https://barnabywalker.github.io/kewr/reference/download_wcvp.html",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 51,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "World Flora Online Plant List",
        "dataset_short_name": "WFO Plant List",
        "notes": "WFO-ID is given in the versioned form (e.g. wfo-0001123862-2024-12) that can be resolved on the WFO Plant List site only. Truncated after the second dash it can be resolved on the WFO site, too.",
        "caveats": "CLB dataset 2004 2025-06-21 [13 jul 2025]",
        "organism_groups": [
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id",
            "name_id_resolved_2_taxon"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "https://wfoplantlist.org/",
        "api_documentation": "https://list.worldfloraonline.org/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 52,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "World Register of Marine Species",
        "dataset_short_name": "WoRMS",
        "notes": "CLB dataset 2011 2025-07-01 [13 jul 2025]",
        "caveats": "ID cited as LSID (e.g. urn:lsid:marinespecies.org:taxname:134241) - the numeric part is the Aphia-ID.",
        "organism_groups": [
            "marine_only",
            "algae",
            "animalia",
            "cyanobacteria",
            "fungi",
            "plantae"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance",
            "classification"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "api",
            "local_installation"
        ],
        "homepage": "https://www.marinespecies.org",
        "api_documentation": "https://www.marinespecies.org/rest/",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    },
    {
        "id": 53,
        "service_name": "Global Names Verifier",
        "dataset_name": "Nomenclator Zoologicus (genera and subgenera)",
        "dataset_short_name": "Nomenclator Zoologicus",
        "notes": "Species are matched to genera (which may be an advantage in this specific case, checking the generic or subgeneric name component of species and infraspecif names).",
        "caveats": "Synonyms are listed as accepted genera.",
        "organism_groups": [
            "contains_fossils",
            "animalia"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [],
        "linkage": [],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "",
        "api_documentation": "",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 54,
        "service_name": "Global Names Verifier",
        "dataset_name": "Index to Organism Names (ION)",
        "dataset_short_name": "ION",
        "notes": "",
        "caveats": "Synonyms are listed as accepted.",
        "organism_groups": [
            "contains_fossils"
        ],
        "geographic_scope": [],
        "purpose": [
            "full_name_checked"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "open_refine_reconciliation_if",
            "api",
            "local_installation"
        ],
        "homepage": "",
        "api_documentation": "",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 0
    },
    {
        "id": 55,
        "service_name": "ChecklistBank Name Match",
        "dataset_name": "Nomenclator Zoologicus (genera and subgenera)",
        "dataset_short_name": "Nomenclator Zoologicus",
        "notes": "CLB dataset \t12639. Integer ids are resolved by appending them to https://www.checklistbank.org/dataset/######/name/, e.g., https://www.checklistbank.org/dataset/126539/name/. [Rod Page]",
        "caveats": "",
        "organism_groups": [
            "contains_fossils",
            "animalia"
        ],
        "geographic_scope": [
            "global",
            "europe",
            "at",
            "be",
            "bg",
            "hr",
            "cz",
            "cy",
            "dk",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "hu",
            "is",
            "ie",
            "it",
            "lv",
            "lt",
            "lu",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "sk",
            "si",
            "es",
            "se",
            "ch",
            "gb"
        ],
        "purpose": [
            "full_name_checked",
            "acceptance"
        ],
        "linkage": [
            "output_persistent_id",
            "output_persistent_resolvable_id"
        ],
        "requirements": [
            "direct_matching_interface",
            "file_matching_interface",
            "download_full_from_website",
            "api",
            "local_installation"
        ],
        "homepage": "",
        "api_documentation": "",
        "direct_matching_restriction": 5000,
        "file_matching_restriction": 1000000
    }
]